### ISSUE TITLE
No keyboard shortcuts after install

### ISSUE THREAD

**Issue by harryfino** [craigmdennis/adobe-xd-nudge-and-resize#13]
I just installed the plugin and I don't have keyboard shortcuts for each of the actions.

![screen shot 2019-01-31 at 3 03 59 pm](https://user-images.githubusercontent.com/1643512/52081967-900bd880-2569-11e9-9a21-0ff80284c535.png)

**Comment by omnivoor** [comment]
@craigmdennis Big thanks for the plugin... Being able to custom nudge with the default shortcuts (cmd + arrow) would be great. Do you think you'll be able to implement this feature soon?

**Comment by craigmdennis** [comment]
You have to define the shortcuts in the MacOS Keyboard settings (search for "keyboard" in Spotlight):

![macos-keyboard](https://user-images.githubusercontent.com/725067/53013267-3a766d80-343d-11e9-9a40-730b7125e472.gif)

**Comment by omnivoor** [comment]
Thanks for the clarification. However "shift + arrow" doesn't seem to nudge as specified by the settings. With another custom shortcut it works fine. For example "shift + cmd + arrow"... So I assume the default shortcuts are restricted?

**Comment by craigmdennis** [comment]
> However "shift + arrow" doesn't seem to nudge as specified by the settings.

Just tested and it works for me fine width CMD + arrow, so it's not a restricted keyboard shortcut. I'm not sure why it wouldn't work unless you had another plugin that is somehow using it. Or a conflicting global MacOS keyboard shortcut. There must be a collision somewhere.

**Comment by omnivoor** [comment]
Ok, for now it works with another shortcut. So that's goog enough for me :) I'll try to find the conflicting app another day. Thanks for the help!

**Comment by craigmdennis** [comment]
Closing the issue. Let me know if you still can't get it working.
