### ISSUE TITLE
idea to put that in xd is really nice but does not work!

### ISSUE THREAD

**Issue by smokeyes** [craigmdennis/adobe-xd-nudge-and-resize#14]
does not work, stays at 10px increments! even going to the settings

**Comment by craigmdennis** [comment]
It will only move by the px you set when using the plugin menu (or keyboard shortcuts).

### Please be more specific with your issue.

- What operating system are you using? Mac or Windows?
- What version of Adobe XD do you have installed?
- What steps are you doing when using the plugin?
- Please provide a screenshot or video of your issue.
