### ISSUE TITLE
Add keyboard shortcuts to plugin?

### ISSUE THREAD

**Issue by johncrim** [craigmdennis/adobe-xd-nudge-and-resize#15]
**Is your feature request related to a problem? Please describe.**
Currently keyboard shortcuts have to be set at the MacOS level - which doesn't work for windows.

**Describe the solution you'd like**
Add keyboard shortcuts to the manifest.json file - keyboard shortcuts are now supported:
https://github.com/AdobeXD/plugin-docs/blob/master/reference/structure/manifest.md

**Comment by craigmdennis** [comment]
Thanks for the link.
While keyboard shortcuts are supported, arrow keys (and punctuation) are not.

> Other keys (including punctuation, arrow keys, or F1-F12) are currently not supported.

I'm happy to add some default shortcuts to help for Windows users. Which would be most useful for you?

**Comment by johncrim** [comment]
Oh - I didn't realize that arrow keys wouldn't work. That's a drag. Is there any indication that will be addressed by Adobe XD?

Picking good general shortcuts is hard, given the lack of arrow key and punctuation support. :(

The best I can come up with is "i" = up, "j" = left, "k" = right, "m" = down. That's a common set of keys for old style keyboard games, which are as good a replacement for arrow keys as I can come up with. 
Then "shift +i" to increase height, "shift + m" to decrease height, "shift + k" to increase width, "shift + j" to decrease width. Then add "+tab" for large increase/decrease.

I'm a bit worried about the confusion with other uses of "i", given that "ctrl + shift +i" is the shortcut for import, and "ctrl + alt + i" is the shortcut for intersect. But I think it should be ok - keyboard shortcuts are more important for this functionality than for importing or intersection (IMO).

I can tweak the manifest locally to try this out, and you could wait to see if anyone else chimes in on this issue.

**Comment by craigmdennis** [comment]
I thought the same but was worried about shortcut collisions.
Let me know if you run into any issues. If they work fine then I'm happy to add those shortcuts for Windows only.

**Comment by axlepascual** [comment]
Adjust size by shortcut plugin used numbers, so we can access it via numpad. Maybe you could use that for now?
https://github.com/littlebusters/Adjust-size-by-shortcut-for-AdobeXD

**Comment by craigmdennis** [comment]
I've added some keyboard shortcuts (Windows only for now) based on the arrows that appear on the number pad.

The update has been submitted to Adobe but you can also download the `.xdx` plugin file from GitHub here: https://github.com/craigmdennis/adobe-xd-nudge-and-resize/releases/tag/v1.1.4. Just double click to install.
